### ISSUE TITLE
Peer Review - Negar Maleki - Lab05

### ISSUE THREAD

**Issue by negarmaleki96** [priyacollins/progdata-class#2]
Peer Review of HW-05 for Priya Singh-Collins
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         |  | :heavy_check_mark: |  |
**Presentation: graphs**    |  |  |  |
**Presentation: tables**    | :heavy_check_mark:  |  |  |
**Achievement, creativity** |  | :heavy_check_mark: |  |
**Ease of access**          |  |  | :heavy_check_mark: |

Remarks:

- *Elaborate on above, esp. for "needs work."*
- *Some specific praise?*
- *Something I learned?*
- *Specific constructive criticism?*
- *Something I know and that you, my peer, might like to know because it is relevant to something you struggled with.*

### Nice work! I think you missed the 3rd part in Lab-05B. Please reconsider that part, and also answer the question. Also, I checked "needs work" for the ease of access part, because I think it is much better if you organize your lab activities in a separate folder.

**Comment by priyacollins** [comment]
Got to both of these parts later on in the semester! Thank you!
