### ISSUE TITLE
Peer Review - Lab 2- Angelina Venetto

### ISSUE THREAD

**Issue by avenetto** [priyacollins/progdata-class#3]
Peer Review of Lab 2 file 
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: |  | |
**Presentation: graphs** | :heavy_check_mark: | |  |
**Presentation: tables** | :heavy_check_mark: |  | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *You did a great job of figuring out the complicated ggplots for the plastic waste data*
- *Some specific praise?- very nice plots, good code logic *
- *Something I learned?- nice job figuring out and completing all of the plots!
- *Specific constructive criticism?- looks good!

**Comment by priyacollins** [comment]
Thank you!
