### ISSUE TITLE
Peer Review - Allison Perusse - Lab 4

### ISSUE THREAD

**Issue by aeperusse** [priyacollins/progdata-class#4]
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *Good job figuring out how to work with the green dataset, I also appreciate the extra time you put into writing out some explanations behind your process. *

**Comment by priyacollins** [comment]
Thank you!
