### ISSUE TITLE
Peer Review of Priya Colllins for Lab 3

### ISSUE THREAD

**Issue by rrorman** [priyacollins/progdata-class#5]
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *Great coding work! Ran without any issues*
- *One specific thing I liked would be how you combined multiple plots in the last chunk.*
- *I learned the importance of drawing functions from other packages.*
- *One thing I would work on would be to explain what your code is doing with your data.*
- *Other than that, great job!*

**Comment by priyacollins** [comment]
Thank you!
