### ISSUE TITLE
Cassandra Richardson - Peer Review of Lab 6 for Priya Singh-Collins

### ISSUE THREAD

**Issue by cassrichardson** [priyacollins/progdata-class#6]
Cassandra Richardson - Peer Review of Lab 6 for Priya Singh-Collins
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark:  | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *Great job on lab 6! Your code is simple, clear and easy to read.*
- *I like how you added comments to explain which question each code chunk was for.*
- *We have almost the exact same code, so I didn't learn anything. Everything seems to look perfect to my understanding!*
- *My only suggestion would be adding comments to explain what each code chunk does.*

**Comment by priyacollins** [comment]
Thank you!
