### ISSUE TITLE
Peer review - Otobo Ujah - Lab 06 #2

### ISSUE THREAD

**Issue by oujah** [priyacollins/progdata-class#7]
Peer Review of Lab 06 for Priya Singh-Collins
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark:| | |
**Presentation: graphs** | | |  |
**Presentation: tables** |  :heavy_check_mark:| | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |

Remarks:
- *It is advisable to use relative paths than the absolute paths*
- *Your coding style was elaborate and neat*

**Comment by priyacollins** [comment]
Thank you!
