### ISSUE TITLE
Peer review Lab 2

### ISSUE THREAD

**Issue by KiprasVarkala** [priyacollins/progdata-class#8]
Peer Review of Lab 2 for Priya Singh Collins
----------------------------------------------------
  Topic | Excellent | Satisfactory | Needs Work |
  ----------------------------|-----|-----|-----|
  **Coding style** | :heavy_check_mark: | | |
  **Coding strategy** | :heavy_check_mark: | | 
  **Presentation: graphs** | :heavy_check_mark: |
  **Presentation: tables** | :heavy_check_mark: | |
  **Achievement, creativity** | :heavy_check_mark: | | |
  **Ease of access** | :heavy_check_mark: | | |

  Remarks:
  - *Code is simple and straightforward. Great work overall!*
  - *I like how you separate out your lines of code to make it easier to read*
  - *I learned some neat things from the reference you provided*
  - *No issues found*
  - *I have learned that it is best to leave reminder comments within the code itself and the interpretation comments below the code to make the output easier to understand.*

**Comment by priyacollins** [comment]
Thank you!
