### ISSUE TITLE
Peer Review - Jude Sullivan - Lab 3

### ISSUE THREAD

**Issue by judesullivan** [priyacollins/progdata-class#9]
**Hello Priya**

Peer Review of Priya's Lab 3
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark:  | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *Starting with the piece of code at line 79, at the end you wrote "na/rm = TRUE" instead of "na.rm = TRUE" which prevented the HTML document from knitting.*
- *Your graphs and tables were clear and easy to interpret.*
- *I think it would help if you annotated your script at the start of each exercise at least because it would show what the exercise asked and how you responded. Nice job overall!!*

**Comment by priyacollins** [comment]
Thank you! Fixed!
